# Generated by Django 3.2.5 on 2021-09-06 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='certTrainer',
            new_name='cert_trainer',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='zipCode',
            new_name='zip_code',
        ),
    ]
