# Generated by Django 3.2.5 on 2021-09-06 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cg', '0002_auto_20210906_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='cert_trainer',
            new_name='certified',
        ),
    ]
